CREATE TYPE LEVEL AS ENUM ("beginner", "intermediate", "advanced")
CREATE TYPE RECURRENCE_PATTERN AS ENUM ("none", "weekly", "biweekly", "monthly")

CREATE TABLE IF NOT EXISTS classes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title VARCHAR(256) NOT NULL,
    description TEXT,
    location VARCHAR(256) NOT NULL,
    capacity INT NOT NULL,
    level LEVEL NOT NULL,
    costume TEXT NOT NULL,
    is_draft BOOLEAN NOT NULL,
    is_recurring BOOLEAN DEFAULT FALSE,
    recurrence_pattern RECURRENCE_PATTERN DEFAULT 'none',
    series_id INTEGER,
    start_date DATE,
    end_date DATE,
    CONSTRAINT class_pkey PRIMARY KEY (id)
)

