CREATE TABLE IF NOT EXISTS class_enrollments (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    student_id INTEGER NOT NULL,
    class_id INTEGER NOT NULL,
    attendance DATE NOT NULL,

    CONSTRAINT Pk_class_enrollments
        PRIMARY KEY(student_id, class_id, id),

    CONSTRAINT fk_student
        FOREIGN KEY(student_id)
        REFERENCES student(id)
        ON DELETE CASCADE,
    
    CONSTRAINT fk_class
        FOREIGN KEY(class_id)
        REFERENCES classes(id)
        ON DELETE CASCADE
)
