DROP TABLE IF EXISTS Events;
DROP TYPE IF EXISTS LEVEL;

CREATE TYPE LEVEL AS ENUM ('beginner', 'intermediate', 'advanced');

CREATE TABLE Events (
    id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),,
    location VARCHAR(256) NOT NULL,
    title VARCHAR(256) NOT NULL,
    description TEXT,
    level LEVEL NOT NULL,
    date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    call_time TIME NOT NULL,
    class_id INTEGER NOT NULL,
    costume TEXT NOT NULL,
    FOREIGN KEY (class_id) REFERENCES Classes(id) ON DELETE CASCADE
);
