CREATE TYPE LEVEL AS ENUM('beginner','intermediate','advanced');


CREATE TABLE Student (  
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    level LEVEL NOT NULL,
    CONSTRAINT fk_user_student FOREIGN KEY (id) REFERENCES User (id)

  );